apps/home/models.py
from apps import db, login_manager
from apps.authentication import blueprint
from apps.authentication.forms import LoginForm, CreateAccountForm
from apps.authentication.models import Users
from apps.authentication.util import verify_pass

# Class Product 
class Product(db.Model):


    __tablename__ = 'products'

    id = db.Column(db.Integer, primary_key=True)
    id_Category = db.Column(db.Integer)
    Name = db.Column(db.String(255))
    Description = db.Column(db.String(255))
    Price = db.Column(db.Float)
    Image = db.Column(db.String(255))

    @staticmethod
    def get_all():
        return Product.query.all()
    
    @staticmethod
    def get_by_id(id):
        return Product.query.get(id)
    

#Class Category
class Category(db.Model):

    __tablename__ = 'category'

    id_Category = db.Column(db.Integer, primary_key=True)
    Name = db.Column(db.String(255))

    @staticmethod
    def get_all():
        return Category.query.all()
    

#Class ProductBySize
class ProductBySize(db.Model):
    __tablename__ = 'productpersize'

    id_ProductSize = db.Column(db.Integer, primary_key=True)
    id_Product = db.Column(db.Integer)
    id_Size = db.Column(db.Integer)
    Stock = db.Column(db.Integer)  # This is the stock field to track available quantities

    @staticmethod
    def get_all():
        return ProductBySize.query.all()
    
    @staticmethod
    def get_by_id(id):
        return Product.query.get(id)

    
#Class Size
class Size(db.Model):
     
    __tablename__ = 'sizes'

    id_Size = db.Column(db.Integer, primary_key=True)
    Name = db.Column(db.String(255))

    @staticmethod
    def get_all():
        return Size.query.all()
    
#Class Cart
class Cart(db.Model):
    __tablename__ = 'cart'

    id_Cart = db.Column(db.Integer, primary_key=True)  # Added a primary key
    id_User = db.Column(db.Integer, db.ForeignKey('users.id'))  # Assuming there is a user model
    id_ProductSize = db.Column(db.Integer, db.ForeignKey('productpersize.id_ProductSize'))
    Quantity = db.Column(db.Integer, default=1)

    product_size = db.relationship('ProductBySize', backref='cart', lazy=True)

    @staticmethod
    def get_by_user(user_id):
        return Cart.query.filter_by(id_User=user_id).all()
    

    #Add Item to the Cart Funcion
    @staticmethod
    def add_item(user_id, product_id, size_id, quantity=1):
        product_size = ProductBySize.query.filter_by(id_Product=product_id, id_Size=size_id).first()

        #If theres not the shirt in the size available display error
        if not product_size:
            raise ValueError("Invalid product or size")

        if product_size.Stock < quantity:
            raise ValueError("Not enough stock")

        cart_item = Cart.query.filter_by(id_User=user_id, id_ProductSize=product_size.id_ProductSize).first()
        if cart_item:
            if cart_item.Quantity + quantity > product_size.Stock:
                raise ValueError("Not enough stock")
            cart_item.Quantity += quantity
        else:
            cart_item = Cart(id_User=user_id, id_ProductSize=product_size.id_ProductSize, Quantity=quantity)
            db.session.add(cart_item)

        db.session.commit()
        return cart_item
    
    @staticmethod
    def delete(id):
        cart_item = Cart.query.get(id)
        if cart_item:
            db.session.delete(cart_item)
            db.session.commit()
            return True
        else:
            return False

apps/home/__init__.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask import Blueprint

blueprint = Blueprint(
    'home_blueprint',
    __name__,
    url_prefix=''
)

apps/home/routes.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from apps.home import blueprint
from flask import render_template, request, redirect, url_for, flash, current_app
from apps.authentication.models import Users
from flask_login import login_required,current_user
from jinja2 import TemplateNotFound
from apps.home.models import Product
from apps.home.models import Category
from apps.home.models import ProductBySize
from apps.home.models import Size
from apps.home.models import Cart
from apps import db

#INDEX - HOME
@blueprint.route('/index')
def index():
    return render_template('home/index.html', segment='index')

#PROFILE
@blueprint.route('/profile')
@login_required
def profile():
    return render_template('home/profile.html', user=current_user)


#UPDATE USERNAME
@blueprint.route('/update_username', methods=['POST'])
@login_required
def update_username():
    new_username = request.form['username']
    if new_username:
        user_id = current_user.id
        if Users.updateName(user_id, username=new_username):
            flash('Username updated successfully!', 'success')
        else:
            flash('Failed to update username.', 'danger')
    return redirect(url_for('home_blueprint.profile'))

#UPDATE EMAIL
@blueprint.route('/update_email', methods=['POST'])
@login_required
def update_email():
    new_email = request.form['email']
    if new_email:
        user_id = current_user.id
        if Users.updateEmail(user_id, email=new_email):
            flash('Email updated successfully!', 'success')
        else:
            flash('Failed to update email.', 'danger')
    return redirect(url_for('home_blueprint.profile'))

#UPDATE PASSWORD
@blueprint.route('/update_password', methods=['POST'])
@login_required
def update_password():
    old_password = request.form['old_password']
    new_password = request.form['new_password']
    
    if old_password and new_password:
        user = current_user
        if Users.update_password(user, old_password, new_password):
            flash('Password updated successfully!', 'success')
        else:
            flash('Old password is incorrect.', 'danger')
    
    return redirect(url_for('home_blueprint.profile'))
    print("teste1")
    return render_template('home/index.html', segment='index')

#SHOP
@blueprint.route('/shop')
def shop():
        print("teste2")
        products = Product.get_all()
        categories = Category.get_all()
        print(products[0].Image)
        print(products)  # Check the products being retrieved
        return render_template('home/shop.html', segment='shop', products=products, categories=categories)

#PRODUCT DETAILS
@blueprint.route('/shop/product/<int:product_id>')
def product_details(product_id):
    try:
        print(f"Fetching details for product_id: {product_id}")
        product = Product.get_by_id(product_id)
        if product is None:
            print("Product not found")
            return render_template('home/page-404.html'), 404

        # Fetch available sizes for the product with stock
        available_sizes = db.session.query(Size, ProductBySize).join(
            ProductBySize, Size.id_Size == ProductBySize.id_Size
        ).filter(
            ProductBySize.id_Product == product_id,
            ProductBySize.Stock > 0
        ).all()
        
        total_stock = sum([product_size.Stock for size, product_size in available_sizes])
        
        print(f"Available sizes: {available_sizes}")

        return render_template('home/product_details.html', product=product, available_sizes=available_sizes, total_stock=total_stock)
    except TemplateNotFound:
        print("Template not found")
        return render_template('home/page-404.html'), 404
    except Exception as e:
        print(f"Exception: {e}")
        return render_template('home/page-500.html'), 500
    

#ADD TO CART
@blueprint.route('/add-to-cart', methods=['POST'])
@login_required
def add_to_cart():
    try:
        product_id = request.form.get('product_id')
        size_id = request.form.get('size_id')
        quantity = int(request.form.get('quantity'))

        print(f"Product ID: {product_id}, Size ID: {size_id}, Quantity: {quantity}")

        Cart.add_item(current_user.id, product_id, size_id, quantity)

        return redirect(url_for('home_blueprint.product_details', product_id=product_id))
    except Exception as e:
        print(f"Exception: {e}")
        return render_template('home/page-500.html'), 500
        

#CART
@blueprint.route('/cart')
@login_required
def cart():
    try:
        # Fetch cart items for the current user
        user_id = current_user.id  # Assuming `current_user` has an `id` attribute
        cart_items = Cart.get_by_user(user_id)
        
        # Collect product details and calculate total price
        cart_details = []
        total_price = 0
        for item in cart_items:
            product_size = ProductBySize.query.get(item.id_ProductSize)
            product = Product.query.get(product_size.id_Product)
            size = Size.query.get(product_size.id_Size)
            
            item_total = product.Price * item.Quantity
            total_price += item_total
            
            cart_details.append({
                'id_Cart': item.id_Cart,
                'product_name': product.Name,
                'product_description': product.Description,
                'product_image': product.Image,
                'product_price': product.Price,
                'size': size.Name,
                'quantity': item.Quantity,
                'item_total': item_total
            })
        
        print(cart_details)
        return render_template('home/cart.html', cart_details=cart_details, total_price=total_price)
    except TemplateNotFound:
        return render_template('home/page-404.html'), 404
    except Exception as e:
        print(f"Exception: {e}")
        return render_template('home/page-500.html'), 500
    

    
# Delete ITEM CARD

@blueprint.route('/delete_item_cart/<int:id>', methods=['POST'])
@login_required
def delete_item_cart(id):
    print(id)
    Cart.delete(id)
    return redirect(url_for('home_blueprint.cart'))



# BUY ITEMS
@blueprint.route('/checkout', methods=['POST'])
@login_required
def checkout():
    try:
        user_id = current_user.id
        cart_items = Cart.get_by_user(user_id)

        # Loop through cart items and update the stock
        for item in cart_items:
            product_size = ProductBySize.query.get(item.id_ProductSize)
            
            if product_size.Stock < item.Quantity:
                flash(f'Not enough stock for product ID {product_size.id_Product}. Only {product_size.Stock} left.', 'danger')
                return redirect(url_for('home_blueprint.cart'))
            
            product_size.Stock -= item.Quantity
            db.session.add(product_size)
        
        db.session.commit()

        # Clear the user's cart after successful purchase
        for item in cart_items:
            db.session.delete(item)
        
        db.session.commit()

        flash('Purchase successful!', 'success')
        return redirect(url_for('home_blueprint.shop'))
    except Exception as e:
        db.session.rollback()
        print(f"Exception: {e}")
        flash('An error occurred during the purchase process. Please try again.', 'danger')
        return redirect(url_for('home_blueprint.cart'))





 # views.py   
@blueprint.route('/<template>')
@login_required
def route_template(template):
    try:
        if not template.endswith('.html'):
            template += '.html'
        segment = get_segment(request)
        return render_template("home/" + template, segment=segment)
    except TemplateNotFound:
        return render_template('home/page-404.html'), 404
    except:
        return render_template('home/page-500.html'), 500

def get_segment(request):
    try:
        segment = request.path.split('/')[-1]
        if segment == '':
            segment = 'index'
        return segment
    except:
        return None

apps/templates/home/cart.html
<!DOCTYPE html>
<html lang="en" itemscope itemtype="http://schema.org/WebPage">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="apple-touch-icon" sizes="76x76" href="/static/assets/img/apple-icon.png">
  <link rel="icon" type="image/png" href="/static/assets/img/favicon.png">

  <title>
    Glory
  </title>

  <!-- Fonts and icons -->
  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900|Roboto+Slab:400,700" />
  <!-- Nucleo Icons -->
  <link href="/static/assets/css/nucleo-icons.css" rel="stylesheet" />
  <link href="/static/assets/css/nucleo-svg.css" rel="stylesheet" />
  <!-- Font Awesome Icons -->
  <script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>
  <!-- Material Icons -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Round" rel="stylesheet">
  <!-- CSS Files -->
  <link id="pagestyle" href="/static/assets/css/material-kit.css?v=3.0.0" rel="stylesheet" />
  <link id="pagestyle" href="/static/assets/css/cards.css" rel="stylesheet" />

  <style>
    body {
      display: flex;
      flex-direction: column;
      justify-content: space-between;
      min-height: 100vh;
      background-image: url('/static/assets/img/background2png.png');
    }

    header {
      background: transparent;
      background-size: cover;
      background-repeat: no-repeat;
      background-attachment: fixed;
      padding-bottom: 10rem;
    }

    .container {
      flex: 1;
      display: flex;
      justify-content: center;
      align-items: center;
    }

    #cartContainer {
      display: flex;
      flex-wrap: wrap;
      width: 80vw;
      justify-content: center;
      align-content: center;
      background-color: rgba(58, 58, 58, 0.815);
      box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
      margin-bottom: 10rem;
    }

    #cartItemsContainer,
    #cartSummaryContainer {
      padding: 2rem;
      color: rgb(197, 197, 197);
    }

    #cartItemsContainer {
      flex: 60%;
    }

    #cartSummaryContainer {
      flex: 40%;
      border-left: 1px solid rgb(197, 197, 197);
      display: flex;
      flex-direction: column;
      justify-content: space-between;
    }

    .cart-item, .cart-item-image {
      display: flex;
      margin-bottom: 1rem;
    }

    .cart-item img {
      max-width: 100px;
      margin-right: 1rem;
    }

    .cart-item-details {
      display: flex;
      flex-direction: column;
      min-width: 20rem;
    }

    .cart-item-details p {
      margin: 0.2rem 0;
    }

    .total-price {
      font-size: 1.5rem;
      font-weight: bold;
    }
    
    #imageProduct{
      max-width: 10vw;
      max-height: 15vh;
    }

    #checkoutButton {
      background-color: rgba(197, 197, 197, 0.966);
      border-style: none;
      align-items: center;
      text-align: center;
      cursor: pointer;
      color: rgb(37, 37, 37);
      padding: 0.4rem;
      border-radius: 0.2rem;
      width: 100%;
    }

    .deleteDiv{
      display: flex;
      width: 50rem;
      flex-direction: column;
      align-items: flex-end;
      

    }

    #deleteButton{
      background-color: rgba(197, 197, 197, 0.966);
      border: 0;
      border-radius: 0.2rem;
    }

  </style>
</head>

<body class="presentation-page bg-gray-200">
  <header>
    {% include 'includes/navigation.html' %}
  </header>

  <div class="container">
    <div id="cartContainer">
      <div id="cartItemsContainer">
        {% for item in cart_details %}
        <div class="cart-item-image">
          <div>
             <img src="./static/assets/img/products/{{ item.product_image }}" alt="Product Image" id="imageProduct">
          </div>
          <div class="cart-item-details">
            <p><strong>{{ item.product_name }}</strong> - {{ item.product_description }}</p>
            <p>Size: <b>{{ item.size }}&nbsp &nbsp &nbsp</b>Quantity: <b>{{ item.quantity }}</b></p>
            <p>Subtotal: ${{ item.item_total }}</p>
          </div>
          <div class="deleteDiv">
            <form action="{{url_for('home_blueprint.delete_item_cart', id=item.id_Cart)}}" method="post">
              <input type="submit" value="X" id="deleteButton">
          </form>
          </div>
        </div>
        {% endfor %}
        <p class="total-price">Total: ${{ total_price }}</p>
        <!-- cart.html -->
        <form action="{{ url_for('home_blueprint.checkout') }}" method="post">
          <button type="submit" id="checkoutButton"> Buy </button>
        </form>

      </div>
    </div>
  </div>

  <!-- FOOTER -->
  <footer class="footer pt-5 " id="footer">

    <div class="container">
      <div class="row align-items-center">
        <div class="col-md-3 mb-4">
  
          <!-- -------- FOOTER LOGO AND NAME OF THE APP ------- -->
          <div>
            <a href="https://appseed.us/apps/flask-apps/flask-material-kit">
              <img src="./static/assets/img/logoProject.png" class="footer-logo" alt="main_logo">
            </a>
            <h6 class="font-weight-bolder mb-4" id="titleFooter">Glory</h6>
          </div>
        </div>
  
         <!-- -------- FOOTER NAVIGATION ------- -->
        <div class="col-md-9">
            <ul class="nav justify-content-center" id="navFooter">
              <li class="nav-item me-3">
                <a class="nav-link" href="https://www.creative-tim.com/presentation" target="_blank">
                  About Us
                </a>
              </li>
              <li class="nav-item me-3">
                <a class="nav-link" href="https://www.creative-tim.com/templates/free" target="_blank">
                  Freebies
                </a>
              </li>
              <li class="nav-item me-3">
                <a class="nav-link" href="https://www.creative-tim.com/templates/premium" target="_blank">
                  Premium Tools
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="https://www.creative-tim.com/blog" target="_blank">
                  Blog
                </a>
              </li>
            </ul>
        </div>
  
         <!-- -------- FOOTER CREDITS TO APPSEED ------- -->
        <div class="col-12">
          <div class="text-center" >
            <p class=" my-4 text-sm font-weight-normal" >
             <a href="https://bit.ly/3fKQZaL"  id="footerCreator" target="_blank">  © Creative Tim - Coded By AppSeed.</a> 
            </p>
          </div>
        </div>
      </div>
    </div>
  </footer>
   <!-- -------- END FOOTER  ------- -->
    <!--   Core JS Files   -->
    <script src="/static/assets/js/core/popper.min.js" type="text/javascript"></script>
    <script src="/static/assets/js/core/bootstrap.min.js" type="text/javascript"></script>
    <script src="/static/assets/js/plugins/perfect-scrollbar.min.js"></script>
    <!--  Plugin for TypedJS, full documentation here: https://github.com/inorganik/CountUp.js -->
    <script src="/static/assets/js/plugins/countup.min.js"></script>
    <!--  Plugin for Parallax, full documentation here: https://github.com/dixonandmoe/rellax -->
    <script src="/static/assets/js/plugins/rellax.min.js"></script>
    <!--  Plugin for TiltJS, full documentation here: https://gijsroge.github.io/tilt.js/ -->
    <script src="/static/assets/js/plugins/tilt.min.js"></script>
    <!--  Plugin for Selectpicker - ChoicesJS, full documentation here: https://github.com/jshjohnson/Choices -->
    <script src="/static/assets/js/plugins/choices.min.js"></script>
    <!--  Plugin for Parallax, full documentation here: https://github.com/wagerfield/parallax  -->
    <script src="/static/assets/js/plugins/parallax.min.js"></script>
    <!-- Control Center for Material UI Kit: parallax effects, scripts for the example pages etc -->
    <!--  Google Maps Plugin    -->
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDTTfWur0PDbZWPr7Pmq8K3jiDp0_xUziI"></script>
    <script src="/static/assets/js/material-kit.min.js?v=3.0.0" type="text/javascript"></script>
    <script type="text/javascript">
      if (document.getElementById('state1')) {
        const countUp = new CountUp('state1', document.getElementById("state1").getAttribute("countTo"));
        if (!countUp.error) {
          countUp.start();
        } else {
          console.error(countUp.error);
        }
      }
      if (document.getElementById('state2')) {
        const countUp1 = new CountUp('state2', document.getElementById("state2").getAttribute("countTo"));
        if (!countUp1.error) {
          countUp1.start();
        } else {
          console.error(countUp1.error);
        }
      }
      if (document.getElementById('state3')) {
        const countUp2 = new CountUp('state3', document.getElementById("state3").getAttribute("countTo"));
        if (!countUp2.error) {
          countUp2.start();
        } else {
          console.error(countUp2.error);
        };
      }
    </script>
  </body>
  </html>
  

apps/templates/home/profile.html
<!DOCTYPE html>
<html lang="en" itemscope itemtype="http://schema.org/WebPage">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="apple-touch-icon" sizes="76x76" href="/static/assets/img/apple-icon.png">
  <link rel="icon" type="image/png" href="./static/assets/img/logoProject.png">
  <title>Glory</title>
  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900|Roboto+Slab:400,700" />
  <link href="/static/assets/css/nucleo-icons.css" rel="stylesheet" />
  <link href="/static/assets/css/nucleo-svg.css" rel="stylesheet" />
  <script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Round" rel="stylesheet">
  <link id="pagestyle" href="./static/assets/css/material-kit.css" rel="stylesheet" />
  <style>
    html, body {
      height: 100%;
      margin: 0;
      display: flex;
      flex-direction: column;
    }

    main {
      flex: 1;
    }

    .navbar {
      position: fixed;
      top: 0;
      width: 100%;
      z-index: 1030;
    }

    .footer {
      background: #f8f9fa;
      width: 100%;
      bottom: 0;
      left: 0;
      right: 0;
      position: relative;
      margin-top: auto;
    }

    #title1 {
      font-size: 2rem;
    }

    .forms {
      background-color: rgba(106, 106, 106, 0.451);
      border-radius: 0.5rem;
      display: flex;
      justify-content: center;
      width: 50%; 
      margin: 0 auto;
      padding: 2rem; 
      text-align: left;
      flex-direction: column;
      position: absolute;
      left: 23%;
    }

    .inputPopUp{
      width: 100%;
      height: 3vw;
      padding: 12px 20px 12px 40px;
      display: inline-block;
      border: 1px solid #b3b0b0;
      border-radius: 4px;
      background-color: #b3b0b0;
    }

    .input-container {
      position: relative;
      width: 100%;
    }

    .input-container input {
      width: 100%;
      padding: 12px 20px 12px 40px;
      display: inline-block;
      border: 1px solid #b3b0b0;
      border-radius: 4px;
      box-sizing: border-box;
      background-color: #b3b0b0;
    }

    .input-container i {
      position: absolute;
      right: 2rem;
      top:70%;
      transform: translateY(-50%);
      color: #6c757d;
      cursor: pointer;
    }

    .form-popup {
      display: none;
      position: fixed;
      top: 50%;
      left: 50%;
      transform: translate(-50%, -50%);
      border: 3px solid #f1f1f1;
      z-index: 9;
      background-color: white;
      padding: 20px;
      border-radius: 10px;
      box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
    }

    .form-container {
      max-width: 400px;
      padding: 10px;
      background-color: white;
    }

    .form-container .btn {
      background-color: #232323;
      color: white;
      padding: 10px 10px;
      border: none;
      cursor: pointer;
      width: 100%;
      margin-top: 1rem;
      opacity: 0.8;
    }

    .form-container .btn.cancel {
      background-color: rgb(133, 130, 130);
    }

    .form-container .btn:hover {
      opacity: 1;
    }
    .form-container h4{
      color: #232323;
    }

    .form-container .text{
      color: #585858;
    }


    .flash-message {
            padding: 10px;
            margin: 10px 0;
        }
        .flash-message.success {
            color: green;
            border: 1px solid green;
            background-color: #e7ffe7;
        }
        .flash-message.danger {
            color: red;
            border: 1px solid red;
            background-color: #ffe7e7;
        }

  </style>
</head>

<body class="presentation-page bg-gray-200">
  <!-- -------- NAV------- -->
  {% include 'includes/navigation.html' %}

  <!-- -------- MAIN CONTENT ------- -->
  <main>
    {% block content %}
    <div class="page-header min-vh-100" style="background-image: url('./static/assets/img/background2png.png')" loading="lazy">
      <div class="forms" id="Content">

        <!-- User Profile Information -->
        <h2 class="text-white" id="title1">Profile Information</h2>
        
        <div class="input-container">
          <label class="form-label text-white">Username</label>
          <!-- -------- Edit button ------- -->
          <i class="fas fa-edit" onclick="openUsernameForm()"></i>
          <input type="text" value="{{ user.username }}" readonly>
        </div>
        
        <br>
        
        <div class="input-container">
          <label class="form-label text-white">Email</label>
          <!-- -------- Edit button ------- -->
          <i class="fas fa-edit" onclick="openEmailForm()"></i>
          <input type="email" value="{{ user.email }}" readonly>
        </div>

        <br>

        <div class="input-container">
          <label class="form-label text-white">Password</label>
          <!-- -------- Edit button ------- -->
          <i class="fas fa-edit" onclick="openPasswordForm()"></i>
          <input type="password" value="******" readonly>
        </div>
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                    <div class="flash-message {{ category }}">{{ message }}</div>
                {% endfor %}
            {% endif %}
        {% endwith %}

      </div>
    </div>

    <!-- --------EDIT EMAIL POPUP------- -->
    <div class="form-popup" id="emailForm">
      <form action="{{ url_for('home_blueprint.update_email') }}" method="post" class="form-container">
        <h4>Edit Email</h4>
        <label for="edit-email-field" class="text"><b>New Email</b></label>
        <input class="inputPopUp" type="email" placeholder="Enter new value" id="edit-email-field" name="email" required>
        <br>
        <button type="submit" class="btn">Save</button>
        <button type="button" class="btn cancel" onclick="closeEmailForm()">Close</button>
      </form>
    </div>

    <!-- --------EDIT NAME POPUP------- -->
    <div class="form-popup" id="usernameForm">
      <form action="{{ url_for('home_blueprint.update_username') }}" method="post" class="form-container">
        <h4>Edit Username</h4>
        <label for="edit-username-field" class="text"><b>New Username</b></label>
        <input class="inputPopUp" type="text" placeholder="Enter new value" id="edit-username-field" name="username" required>
        <br>
        <button type="submit" class="btn">Save</button>
        <button type="button" class="btn cancel" onclick="closeUsernameForm()">Close</button>
      </form>
    </div>

    <!-- --------EDIT PASSWORD POPUP------- -->
    <div class="form-popup" id="passwordForm">
      <form action="{{ url_for('home_blueprint.update_password') }}" method="post" class="form-container">
        <h4>Edit Password</h4>
        <label for="edit-password-old-field" class="text"><b>Old Password</b></label>
        <input class="inputPopUp" type="password" placeholder="Enter old password" id="edit-password-old-field" name="old_password" required>
        <br>
        <label for="edit-password-field" class="text"><b>New Password</b></label>
        <input class="inputPopUp" type="password" placeholder="Enter new value" id="edit-password-field" name="new_password" required>
        <br>
        <button type="submit" class="btn">Save</button>
        <button type="button" class="btn cancel" onclick="closePasswordForm()">Close</button>
    </form>
    </div>

    {% endblock content %}
  </main>

  <!-- -------- FOOTER ------- -->
  {% include 'includes/footer.html' %}

  <!-- Core JS Files -->
  <script src="/static/assets/js/core/popper.min.js" type="text/javascript"></script>
  <script src="/static/assets/js/core/bootstrap.min.js" type="text/javascript"></script>
  <!-- (other JS files) -->

  <script type="text/javascript">
    function openEmailForm() {
      document.getElementById("emailForm").style.display = "block";
    }

    function closeEmailForm() {
      document.getElementById("emailForm").style.display = "none";
    }

    function openUsernameForm() {
      document.getElementById("usernameForm").style.display = "block";
    }

    function closeUsernameForm() {
      document.getElementById("usernameForm").style.display = "none";
    }

    function openPasswordForm() {
      document.getElementById("passwordForm").style.display = "block";
    }

    function closePasswordForm() {
      document.getElementById("passwordForm").style.display = "none";
    }
  </script>
</body>
</html>